### PR TITLE
Replace dokku-installer.rb with dokku-installer.py

### LINKED ISSUE #1783: Install is broken for Debian
I get a 'bad Gateway' when trying to get to the web-admin after a fresh install depicted in /docs/getting-started/install/debian.md ([here](http://dokku.viewdocs.io/dokku/getting-started/install/debian/) online) on a system with debian (stable) Jessie.

I tracked down the bug to be sinatra not loading because `apt-get` pre-installs `rubygem-sinatra` from the ppa we just added (https://packagecloud.io/dokku/dokku/ubuntu/ trusty main). This package installs the gem for an incorrect version of ruby (1.9 instead of the default 2.1 on Debian Jessie).

3 remarks:

1. Am I right to try to install Dokku following these instructions on debian? If these are Ubuntu specific, it needs to be mentionned... If it's supposed to be debian compatible, then we gotta fix it :-)
1. Was there a proper way to debug that? I tracked down the bug by actually restarting myself the dokku-installer init script (that failed with sinatra not found).
1. For those who got the same problem, installing the correct packages and restart the init script did the trick:
```
sudo apt-get install ruby-rack ruby-rack-protection ruby-sinatra ruby-tilt
sudo sh /etc/init/dokku-installer.conf &
```

### PR DESCRIPTION
**Pull request by josegonzalez**
The python version should allow us to remove any ruby dependencies and should also slightly speed up dokku installation. All LSB-compliant distributions should have python, so we should be okay depending upon it.

Closes #1783
Closes #1786

### CODE REVIEW

**Comment by josegonzalez** [comment]
Tested against ubuntu and works fine :)

**Comment by michaelshobbs** [comment]
I'm +1 for anything that `--` ruby code :stuck_out_tongue_closed_eyes:

**Comment by josegonzalez** [comment]
I'm going to merge this. If there are any issues in usage, we can sort them out after the release.

**Comment by antoine-lizee** [comment]
LGTM! Thanks for this. Unfortunately I don't really have the skills/time to quickly test it on a fresh Debian install right now, but I don't see why it wouldn't work. Will make sure to try it next time I install dokku on Debian.

**Pull request merged**
