### PR TITLE
Simplify vhost setting

### PR DESCRIPTION
**Pull request by josegonzalez**
Not sure what the difference is between the two files, but if tests pass, then surely the `HOSTNAME` isn't necessary?

### CODE REVIEW

**Comment by michaelshobbs** [comment]
IIRC, `HOSTNAME` can be an IP but `VHOST` cannot.

**Comment by josegonzalez** [comment]
When are we supposed to use one over the other?

**Comment by michaelshobbs** [comment]
That's a good question. Originally VHOST was just for nginx config. If that wasn't populated, we'd use HOSTNAME for printing out app urls

**Comment by josegonzalez** [comment]
So why do we sometimes refer to HOSTNAME in our codebase? Seems a bit wacky to have both...

**Comment by michaelshobbs** [comment]
If I understand the original intent, `HOSTNAME` is for the host itself and `VHOST` is for the default domain for all apps. Then of course there's `VHOST` in the app directory. 

My 2 cents: I think we should leave it as is and make the docs more clear.

**Pull request closed without merging**
