### PR TITLE
add support for set DOKKU_IMAGE per app

### LINKED ISSUE #2745: Ability to specify base image in app or plugin
Hello, in some cases it could be handy if the application itself or eventually a plugin could set some custom base image before the buildpacks are applied.

Today one can do that with the dokkurc file. But this is system wide then and this can be a bit annoying. I looked at the current code if I could change the DOKKU_IMAGE in a plugin hook such as post-extract (so based on some app file analysis I would like to eventually switch the base image) but I couldn't figure out anything. If I try to export DOKKU_IMAGE again it doesn't override the value where it is called.

Currently, the DOKKU_IMAGE is set by sourcing dokkurc or setting its default value in the dokku executable and it is used in:
```
plugins/common/functions:      local id=$(docker run $DOKKU_GLOBAL_RUN_ARGS -d -v $CACHE_DIR:/cache -e CACHE_PATH=/cache $DOCKER_ARGS $IMAGE /build)
```

Is there any way to override it? Any simple refactor I could contribute to allow it? Thanks.

### PR DESCRIPTION
**Pull request by fzerorubigd**
fixes #2745

### CODE REVIEW

**Comment by josegonzalez** [comment]
Needs a test of some sort.

**Comment by fzerorubigd** [comment]
I can not find a way to check for the base image. a way is to create an image with specific file in it and the check for that specific file after build.

**Comment by josegonzalez** [comment]
@fzerorubigd that works for me. Can you fork herokuish and add some change to make it possible to test? We can then probably merge that into a custom branch, make a tag of it on docker hub, and then use that for the test here.

**Comment by fzerorubigd** [comment]
@josegonzalez is that really required? why not simply run herokuish, create a file in it and then tag it as new image and not adding an external dependency to an image to pull?
Am I missing something?

**Comment by josegonzalez** [comment]
Sure thats fine.

**Comment by rvalyi** [comment]
many tanks for this feature!

**Pull request merged**
