### PR TITLE
Fixed `getting-started`-document

### PR DESCRIPTION
**Pull request by weyert**
Fixed `getting-started`-document so it doesn't refer to deprecated calls

### CODE REVIEW

**Comment by josegonzalez** [comment]
They are only recently deprecated, so the new call doesn't work on old systems. As the old call redirects the warning to stderr, this is fine.

**Comment by weyert** [comment]
But shouldn't doc reflect the state of `master`?

**Comment by josegonzalez** [comment]
Yes and no. In this case, developers are likely coming in to upgrade _to_ master. Once we hit a few more minor releases (or a major) then we can consider removing the deprecated call imo.

**Comment by weyert** [comment]
Okay :) I will keep the branch for later reference then

**Pull request closed without merging**
