### PR TITLE
Improve docs for default site with HTTPS

### PR DESCRIPTION
**Pull request by zuck**
Provide a working solution of default site configuration for both HTTP and HTTPS requests.

### CODE REVIEW

**Comment by josegonzalez** [comment]
I don't think that will work all the way. Pretty sure browsers will see the catch-all and try to render with that ssl certificate, but fail because it won't be valid for the arbitrary domain.

Have you tested this to ensure it works as expected?

**Comment by zuck** [comment]
Well, on my production server it works with wildcard cert. Actually I'm returning 404 instead of 410.

**Comment by josegonzalez** [comment]
Okay so that makes sense, but it wont work for any arbitrary server - many of our users do not have a wildcard cert.

Mind updating the docs to make that caveat clear? This will only work when the ssl certificate is valid for the domain being requested.

**Comment by zuck** [comment]
I've expanded docs a bit, hoping it's more clear now.

**Comment by joshmanders** [comment]
Yeah but to use wildcard certs with the letsencrypt plugin isn't an easy task as it required DNS validation.

**Pull request merged**
