### PR TITLE
Build a custom dhparam file once for nginx and include it as default

### PR DESCRIPTION
**Pull request by bitmand**
MR to solve #2984 

Please be aware that this is mostly harmless, but:

* It depends on the `openssl` command
* It will take a little bit of time and generate some output the first time this is run
* Also, I have no idea if this is actually the preferred Dokku way of solving this :)

### CODE REVIEW

**Comment by bitmand** [comment]
I checked the failed circleci build, but it does not seem related to my changes.

**Comment by josegonzalez** [comment]
Does this break existing SSL certificates?

**Comment by bitmand** [comment]
@josegonzalez No it does not.

The actual SSL Labs test is here, with more information:
https://www.ssllabs.com/ssltest/analyze.html?d=gorm.longboat.io&s=139.162.162.128

The security issue explained: https://weakdh.org/

Also some information on how to fix: https://weakdh.org/sysadmin.html - specifically:

> Use a Strong, Diffie Hellman Group. A few 1024-bit groups are used by millions of servers, which makes them an optimal target for precomputation, and potential eavesdropping. Administrators should use 2048-bit or stronger Diffie-Hellman groups with "safe" primes.

..that's why if Dokku just generates this file randomly per installation and includes it in the nginx config, it fixes the problem :)

**Comment by josegonzalez** [comment]
Right but if we add a new file, does that break anyone's already provisioned ssl certificates? And how does that impact people overriding this one-off at a different level? Want to make sure we have that well documented.

**Comment by bitmand** [comment]
@josegonzalez 

> Right but if we add a new file, does that break anyone's already provisioned ssl certificates?

No it doesn't. This isn't related to the certificates, neither already installed or in the future.
It's a setting for the TLS handshake and the encryption of the TLS connection, that fixes a security issue.

> And how does that impact people overriding this one-off at a different level? Want to make sure we have that well documented.

Are you are thinking of the cases where people have already fixed this with custom nginx config? It should be able to co-exist (both in the http and server settings), but I can test this, if you want me to?

**Comment by josegonzalez** [comment]
Please test

**Pull request merged**
