### PR TITLE
Add the ability to run containers in detached mode

### PR DESCRIPTION
**Pull request by josegonzalez**
This emulates heroku's one-off containers feature.

### CODE REVIEW

**Comment by michaelshobbs** [comment]
How do we manage said container after it's been detached?

**Comment by josegonzalez** [comment]
It spits out a container id and it's up to the user to do something with that container ID if necessary.

**Comment by michaelshobbs** [comment]
Might be good to capture that in the docs

**Comment by josegonzalez** [comment]
Updated that in docs.

**Comment by michaelshobbs** [comment]
Does this work if you run it from the console? Specifically, I don't think you can use `-it` and `--detach` together, right?

**Comment by josegonzalez** [comment]
It definitely spins off the container and runs the task I want on the cli.

**Pull request merged**
