### PR TITLE
[config] forward output from plugn triggers to user

### PR DESCRIPTION
**Pull request by alexquick**
The config plugin was suppressing the output from `post-config-update` and `app-restart`

### CODE REVIEW

**Comment by josegonzalez** [comment]
Guess there isn't a good way to stream the output to stdout/stderr?

**Comment by alexquick** [comment]
As it is now, yeah there's no way to do it.  This is the only file that uses `PlugnTrigger`, so I can change the implementation to always stream stderr/stdout if that's preferable.

**Comment by josegonzalez** [comment]
If you have a moment, that would be great.

**Comment by alexquick** [comment]
@josegonzalez how's this look?

**Comment by josegonzalez** [comment]
Thanks for the pull request!

**Pull request merged**
