### PR TITLE
docs: CHECKS only matches start of content

### PR DESCRIPTION
**Pull request by Tyilo**
Right?

[ci skip]

### CODE REVIEW

**Comment by josegonzalez** [comment]
Thanks for the pull request!

**Comment by ilyapoz** [comment]
Wait a minute, what do you mean by start?

**Comment by josegonzalez** [comment]
Actually didn't read this closely. I think it just greps all the output for what you specified. Not just the first but of text in the output. Not sure what @Tylio meant now upon rereading.

**Comment by Tyilo** [comment]
Hmm, I thought that it worked that way. Maybe my testing was wrong.

We should still probably document exactly how the matching (it must be a substring of the page or is it a regex?)

**Comment by ilyapoz** [comment]
looks like this is the check fwiw https://github.com/dokku/dokku/blob/2fbe5a418ff4f93d1c3b66e9cf9fa257728cbc9c/plugins/checks/check-deploy#L211

**Comment by josegonzalez** [comment]
Thats a regex check.

**Pull request merged**
