### PR TITLE
Use correct port number for the upstream.

### PR DESCRIPTION
**Pull request by cstroe**
This is a quick fix for #2857 

Investigating how to write tests around it.

### CODE REVIEW

**Comment by josegonzalez** [comment]
This reverts a previous change. We should instead look at why we're not outputting the correct exposed port in the `DOKKU_APP_LISTENERS`.

**Comment by cstroe** [comment]
The `DOKKU_APP_LISTENERS` variable is constructed [here](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/functions#L221).

I enabled line-by-line debugging for bash and got the following:

```
root@dokku:/var/lib/dokku/plugins/enabled/nginx-vhosts# dokku proxy:ports-add gogs http:333:333
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP: http:2222:22 http:3000:3000 http:333:333
+ [[ -z '' ]]
+ [[ -z '' ]]
+ shopt -s nullglob
+ local DOKKU_APP_IP_FILE
+ for DOKKU_APP_IP_FILE in '$DOKKU_ROOT/$APP/IP.web.*'
+ local DOKKU_APP_PORT_FILE=/home/dokku/gogs/PORT.web.1
+ local DOKKU_APP_LISTENER_IP=172.17.0.5
+ local DOKKU_APP_LISTENER_PORT=22
+ local 'DOKKU_APP_LISTENERS+=172.17.0.5:22 '
++ echo '172.17.0.5:22 '
++ xargs
+ local DOKKU_APP_LISTENERS=172.17.0.5:22
+ shopt -u nullglob
+ set +x
-----> Configuring gogs.dokku.lan...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
```

So, because there's only one file that matches `'$DOKKU_ROOT/$APP/IP.web.*'`, the second port never gets detected.

In the app directory there is indeed only one port detected:
```
root@dokku:/home/dokku/gogs# ls -la
total 60
drwxr-xr-x 2 dokku dokku 4096 Aug  4 04:34 .
drwxr-xr-x 5 dokku dokku 4096 Aug  4 02:43 ..
-rw-r--r-- 1 dokku dokku   65 Aug  4 03:14 CONTAINER.web.1
-rw-r--r-- 1 dokku dokku  208 Aug  4 03:14 DOCKERFILE_ENV_FILE
-rw-r--r-- 1 dokku dokku   53 Aug  4 02:37 DOCKER_OPTIONS_BUILD
-rw-r--r-- 1 dokku dokku  124 Aug  4 02:38 DOCKER_OPTIONS_DEPLOY
-rw-r--r-- 1 dokku dokku  100 Aug  4 02:38 DOCKER_OPTIONS_RUN
-rw-r--r-- 1 dokku dokku    6 Aug  4 02:41 DOKKU_SCALE
-rw------- 1 dokku dokku  259 Aug  4 04:34 ENV
-rw-r--r-- 1 dokku dokku   11 Aug  4 03:14 IP.web.1
-rw------- 1 dokku dokku 4922 Aug  4 04:34 nginx.conf
-rw-r--r-- 1 dokku dokku    3 Aug  4 03:14 PORT.web.1
-rw-r--r-- 1 dokku dokku  104 Aug  4 04:34 URLS
-rw-r--r-- 1 dokku dokku   15 Aug  4 02:41 VHOST
```

**Comment by cstroe** [comment]
After more debugging it seems that there is a 1:1 relationship between an `IP.web.` file and a container running an app.  Since I'd never need to scale Gogs to more than one instance, only `IP.web.1` will ever exist.

So `DOKKU_APP_LISTENERS` will only ever contain one entry per container, even though each container might `EXPOSE` more than one port.

Since we're configuring the app with proxy commands in the first place, it might make more sense to use `DOKKU_PROXY_PORT_MAP`:

```
root@dokku:/home/dokku# dokku config:get gogs DOKKU_PROXY_PORT_MAP
http:2222:22 http:3000:3000
```

And this is the `sigil` command:

```
+ sigil -f /var/lib/dokku/plugins/available/nginx-vhosts/templates/nginx.conf.sigil 
  APP=gogs DOKKU_ROOT=/home/dokku NOSSL_SERVER_NAME= 
  DOKKU_APP_LISTENERS=172.17.0.3:22 DOKKU_LIB_ROOT=/var/lib/dokku 
  PASSED_LISTEN_IP_PORT= SPDY_SUPPORTED=false HTTP2_SUPPORTED=false 
  DOKKU_APP_LISTEN_PORT= DOKKU_APP_LISTEN_IP= APP_SSL_PATH=/home/dokku/gogs/tls 
  SSL_INUSE= SSL_SERVER_NAME= NGINX_PORT= NGINX_SSL_PORT= 'RAW_TCP_PORTS=22 3000' 
  'PROXY_PORT_MAP=http:2222:22 http:3000:3000' 'PROXY_UPSTREAM_PORTS=22 3000'
```

# Possible approaches
1. Use `PROXY_UPSTREAM_PORTS` to build the upstream section of the `nginx.conf` and stop using `DOKKU_APP_LISTENERS` there.
2. Something else?

**Comment by cstroe** [comment]
This issue was caused by the fix from https://github.com/dokku/dokku/issues/2676

In #2676, it seems that rather than removing the unused variable `$listener_port`, it was decided to make it used again.  But since the `DOKKU_APP_LISTENERS` variable has a different meaning (it's only reliable to extract only the IP of each upstream container, not the upstream ports), the port should still be configured via `$upstream_port`, which is correctly parsed from `PROXY_UPSTREAM_PORTS`.

**Comment by cstroe** [comment]
@josegonzalez I made the fix to `nginx.conf.sigil` and related code in `test_helper.bash`.

I'm going to try to write a test around this.

**Comment by gastonmorixe** [comment]
Thank you.

**Pull request merged**
