### PR TITLE
Added a comment about Dockerfile deployment

### PR DESCRIPTION
**Pull request by francipvb**
I found issues while trying to deploy an app from a dockerfile and I found that the expose instruction causes problems with the dokku proxy. I found the solution and I am contributing it.

### CODE REVIEW

**Comment by josegonzalez** [comment]
When you say it is exposed on the incorrect port, what did you find it was exposed on?

**Comment by francipvb** [comment]
Hello,

The default HTTP port is 80 and if you specify in the dockerfile that you expose the port 8888 you'll have to set up the proxy manually. That means the default nginx page is displayed.

However, if you don't add the `EXPOSE` instruction the proxy is set up correctly and the application is presented as expected.

**Comment by josegonzalez** [comment]
Do you have an example Dockerfile app that doesn't work as expected and the change that you performed to make it work as expected?

**Comment by francipvb** [comment]
Hello,

See this dockerfile:

```
FROM python:3.9 AS base

ARG DJANGO_SETTINGS_MODULE

WORKDIR /app

RUN pip3 --no-cache-dir install poetry \
    && poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-dev --no-root

COPY . ./

COPY ./docker/entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENV DJANGO_SETTINGS_MODULE="vectorvgt.settings.runtime"

RUN python manage.py collectstatic --no-input
RUN chmod +x ./docker/post_deploy.sh

EXPOSE 8000
ENTRYPOINT [ "/entrypoint.sh" ]
CMD daphne -b 0.0.0.0 vectorvgt.asgi:application
```

And here is the procfile:

```
web: daphne -b 0.0.0.0 -p $PORT vectorvgt.asgi:application
release: python manage.py migrate
worker: celery --application vectorvgt.celery:app worker --events
beat: celery --application vectorvgt.celery:app beat --events
```

This app won't be presented in the default HTTP port. Insthead the default nginx page will be presented.

To fix this issue, I just removed the `EXPOSE` instruction.

**Comment by josegonzalez** [comment]
Right, when you set an `EXPOSE` directive and have the nginx proxy enabled, we use that port as the mapping. So nginx listens on port `8000` and routes that to the container. The port mapping is thus `http:8000:8000` (`scheme:host-port:container-port`).

That is documented [here](https://dokku.com/docs/networking/port-management/#usage) under port management (and that section is linked to from [here](https://dokku.com/docs/deployment/builders/dockerfiles/#exposed-ports).

Unfortunately, nginx does fallback routing, so if there is already a site set (which is usually something like `/etc/nginx/sites-enabled/00-default`), then it'll route to that if there is no matching vhost:port server block for the request.

I think your doc link might need a bit more explanation as to why not using an EXPOSE might help. I'll update the PR.

**Comment by francipvb** [comment]
I see.

What happen if you push changes to the app?

**Comment by josegonzalez** [comment]
I think the doc update I wrote clarifies things. Can you check the diff?

**Comment by francipvb** [comment]
Thank you, seems better than mine.

**Comment by josegonzalez** [comment]
Awesome, I'll merge it then.

**Pull request merged**
