### PR TITLE
Traefik optional custom http https entrypoints

### PR DESCRIPTION
**Pull request by Coffee2CodeNL**
The code changes add the capability to configure custom HTTP and HTTPS entry points for the Traefik virtual hosts plugin. New settings have been added to the list of valid and global keys. Also, function definitions for retrieving default HTTP and HTTPS entry points were included in the internal functions file. Furthermore, the 'docker-args-process-deploy' script now considers the new entry points while processing deployment arguments.

### CODE REVIEW

**Comment by josegonzalez** [comment]
What is the use case here?

**Comment by Coffee2CodeNL** [comment]
I'm not using Dokku's Traefik instance, my entrypoints are "web" and "websecure", so this is for when you're routing through an existing Traefik instance.

**Comment by josegonzalez** [comment]
Seems legit. I wonder if we should change our defaults...

Anyways:

- this needs to be in the report output
- needs documentation
- needs a unit test

**Comment by Coffee2CodeNL** [comment]
Everything should be good for merge now :)

**Pull request merged**
