### PR TITLE
Remove potentially bad nginx template examples

### LINKED ISSUE #3068: validate_nginx failed / invalid number of arguments in "server_name" << using template from docs
First of all, cool project 👍 . I was looking for something like that to deploy my python apps ASAP with custom domains and https certs. This is what i am looking for, but already i faced same issues like in other projects of this type. I dived into docs but they are not clear, i want to perform really simple steps.
If the problems i am facing may be expected behaviour of dokku, may someone explain to me what i am doing wrong and how to achieve my expected results in a better way?

Also a question i couldnt find in docs (theres no search in docs?):
Why there are multiple docker containers for my app as i perform more deploys?
Why they are not automatically deleted and keep runing (dokku cleanup does not help).
If my python app is a flask application running on port 80 via gunicorn in Procfile, will that cause issues beacuse i have to expose port 443 for the SSL to work?)

**Expected Results:**
1. Create a new repository (python app) with a custom domain name (from what i understand, naming my app: mydomain.tld should setup everything for me, as docs are saying: adding domain before the app may cause issues).
2. Push it with custom nginx config ( i want to redirect www version to non-www).
3. Setup SSL via letsencrypt plugin ( from what i understand dokku will automatically handle redirection of http to https).
3. Repeat with new app & domain

As you see this looks really simple and this is why i am diving into this project. It looks awesome 🥇 

**Description of problem:**
- When using custom nginx config (copied from docs, nothing added or changed) i receive nginx configuration problem as seen in actual results.
- When not using custom nginx config app is deployed and works.

**How was Dokku installed?:**
Digitalocean, its a fresh install and nothing is done on it.

**Steps to Reproduce:**
1. custon nginx.conf.sigil (copied from docs, nothing changed, check in custom config below for content)
2. git init. && git add . && git commit
3. git remote add dokku dokku@dokku.me:**mydomain.tld**
4. git push dokku master

**Actual Results with custom config:**
````
remote: -----> Cleaning up...
remote: -----> Building mydomain.tld from herokuish...
remote: -----> Adding BUILD_ENV to build environment...
remote:        -----> Python app detected
remote:        !     The latest version of Python 3 is python-3.6.2 (you are using python-3.6.4, which is unsupported).
remote:        !     We recommend upgrading by specifying the latest version (python-3.6.2).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing requirements with pip
remote:
remote:        -----> Discovering process types
remote:        Procfile declares types -> web
remote: -----> Releasing mydomain.tld (dokku/mydomain.tld:latest)...
remote: -----> Deploying mydomain.tld (dokku/mydomain.tld:latest)...
remote: -----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
remote: -----> App Procfile file found (/home/dokku/mydomain.tld/DOKKU_PROCFILE)
remote: -----> DOKKU_SCALE file found (/home/dokku/mydomain.tld/DOKKU_SCALE)
remote: =====> web=1
remote: -----> Attempting pre-flight checks
remote:        For more efficient zero downtime deployments, create a file CHECKS.
remote:        See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
remote:        CHECKS file not found in container: Running simple container check...
remote: -----> Waiting for 10 seconds ...
remote: -----> Default container check successful!
remote: -----> Running post-deploy
remote: -----> Found previous container(s) (12de4f551a10) named mydomain.tld.web.1
remote: =====> renaming container (12de4f551a10) mydomain.tld.web.1 to mydomain.tld.web.1.1518895508
remote: =====> renaming container (9c29d9d0822e) sad_stallman to mydomain.tld.web.1
remote: -----> VHOST support disabled. Skipping domains setup
remote: -----> Overriding default nginx.conf with detected nginx.conf.sigil
remote: -----> Creating http nginx.conf
remote: -----> Running nginx-pre-reload
remote:        Reloading nginx
remote: nginx: [emerg] invalid number of arguments in "server_name" directive in /home/dokku/mydomain.tld/nginx.conf:4
remote: nginx: configuration file /etc/nginx/nginx.conf test failed
remote:        validate_nginx failed. contents of /home/dokku/mydomain.tld/nginx.conf below...
remote: server {
remote:   listen      [::]:42318;
remote:   listen      42318;
remote:   server_name ;
remote:   access_log  /var/log/nginx/mydomain.tld-access.log;
remote:   error_log   /var/log/nginx/mydomain.tld-error.log;
remote:
remote:   # set a custom header for requests
remote:   add_header X-Served-By www-ec2-01;
remote:
remote:   gzip on;
remote:   gzip_min_length  1100;
remote:   gzip_buffers  4 32k;
remote:   gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
remote:   gzip_vary on;
remote:   gzip_comp_level  6;
remote:
remote:   location    / {
remote:     proxy_pass  http://mydomain.tld;
remote:     proxy_http_version 1.1;
remote:     proxy_set_header Upgrade $http_upgrade;
remote:     proxy_set_header Connection "upgrade";
remote:     proxy_set_header Host $http_host;
remote:     proxy_set_header X-Forwarded-Proto $scheme;
remote:     proxy_set_header X-Forwarded-For $remote_addr;
remote:     proxy_set_header X-Forwarded-Port $server_port;
remote:     proxy_set_header X-Request-Start $msec;
remote:   }
remote:   include /home/dokku/mydomain.tld/nginx.conf.d/*.conf;
remote: }
remote:
remote: upstream mydomain.tld {
remote:
remote:   server 172.17.0.6:5000;
remote:
remote: }
To dokku.me:mydomain.tld
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku.me:mydomain.tld'
````
**Actual nginx.conf without custom config:**
````
server {
  listen      [::]:42318;
  listen      42318;

  access_log  /var/log/nginx/mydomain.tld-access.log;
  error_log   /var/log/nginx/mydomain.tld-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://mydomain.tld-5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/mydomain.tld/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

}

upstream mydomain.tld-5000 {

  server 172.17.0.7:5000;
}
````
Custom config :

````
server {
  listen      [::]:{{ .NGINX_PORT }};
  listen      {{ .NGINX_PORT }};
  server_name {{ .NOSSL_SERVER_NAME }};
  access_log  /var/log/nginx/{{ .APP }}-access.log;
  error_log   /var/log/nginx/{{ .APP }}-error.log;

  # set a custom header for requests
  add_header X-Served-By www-ec2-01;

  gzip on;
  gzip_min_length  1100;
  gzip_buffers  4 32k;
  gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
  gzip_vary on;
  gzip_comp_level  6;

  location    / {
    proxy_pass  http://{{ .APP }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include {{ .DOKKU_ROOT }}/{{ .APP }}/nginx.conf.d/*.conf;
}

upstream {{ .APP }} {
{{ range .DOKKU_APP_LISTENERS | split " " }}
  server {{ . }};
{{ end }}
}

server {
    server_name www.{{ .NOSSL_SERVER_NAME }};
    return 301 $scheme://{{ .NOSSL_SERVER_NAME }}$request_uri;
}
````

### PR DESCRIPTION
**Pull request by josegonzalez**
These examples do not include _all_ of the contents of the original template. Rather than having to keep them up to date and confuse users when we don't, lets just remove them. The section above contains a link to the current `nginx.conf.sigil` and should be referenced by our users instead.

Closes #3068

[ci skip]

**Note:** If this PR is just doc changes, please put [ci skip] in the body that way tests do not run.

### CODE REVIEW

**Comment by seospace** [comment]
Can't we just provide a link in docs to https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil as an example ?

**Comment by josegonzalez** [comment]
Thats [here](https://github.com/dokku/dokku/pull/3069/files#diff-b224ceacbc7527330f8308ef201f9821R24).

**Comment by seospace** [comment]
Yes i just found that, damn man you are fast keep up the good work lesson learned from you thanks ;)
P.S what you eat for breakfast?

**Comment by josegonzalez** [comment]
A large bottle of theraflu for my cough.

**Pull request merged**
