### PR TITLE
Add deploy with GitHub Actions doc

### PR DESCRIPTION
**Pull request by badsyntax**
I noticed that building docker images can negatively affect my runtime apps performance, so I setup builds in CI using [these docs as a guide](http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-an-image-from-ci).

I think adding docs specific to GitHub Actions might be useful for others.

### CODE REVIEW

**Comment by josegonzalez** [comment]
While I understand the use case, I think we're conflating github actions with loading a remote image - something already documented [here](http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-an-image-from-ci). Any reason why that doc doesn't suffice (other than not filling in the other Github Actions bits)?

I think the upcoming work in #4151 neatly handles the general Github Actions use case. Going to close this for now.

**Comment by badsyntax** [comment]
> I think we're conflating github actions with loading a remote image - something already documented here

I don't follow. The purpose of this PR was to provide an example of how to automate (with CI) what's mentioned in the docs. Now I could be missing something but I don't see how this use case is covered by https://github.com/dokku/github-action.

> Any reason why that doc doesn't suffice (other than not filling in the other Github Actions bits)?

I could ask the same about about the reason for building https://github.com/dokku/github-action - it's about making life a little easier for dokku users.

I personally feel that building docker images on a runtime server is a bad idea. My first experience of using dokku was experiencing degraded runtime performance due to this approach. 

Would you consider adding this use case (building an image in CI and loading it with dokku remotely) to https://github.com/dokku/github-action?

**Comment by josegonzalez** [comment]
A few things:

- The problem with your doc addition is that it is a specific, already documented workflow tailored to a specific CI environment. Folks will want that same example on other CI systems, and I don't wish to do that.
-  Yes, we have a Gitlab-specific example that is contrary to my first point, but that will actually be removed in favor of #3433.
- Part of the work for all the CI docs is to unify the workflows so there is one single image - https://github.com/dokku/ci-docker-image - that handles the general integration for all CI systems. Adding support there is the correct place, and then we'd flow that through everywhere else.
- Your workflow actually doesn't make things simpler.
  - It only deploys on release creation, whereas a more common workflow is on push to the `master`/`main` branch.
  - It assumes the user will enable root access for deploys, which is the opposite of what we want to enable (all actions should flow through the dokku user).
- Yes, I could have merged this as is, but then I'd have to do the extra work to delete it later and break links.
- The workflow uses docker commands directly. This has never been great, and while I've never had a use case for it, we should probably have something in the core for it. I filed #4219 to enable that work.

**Comment by josegonzalez** [comment]
0.24.0 will have the `git:from-image` command, which will support this sort of workflow by embedding the image pulling into the `Dockerfile` being built :)

**Pull request closed without merging**
