### PR TITLE
Tweak the checks example documentation

### PR DESCRIPTION
**Pull request by trevorturk**
I took a pass at cleaning up the `checks-example` documentation re: https://github.com/dokku/dokku/issues/1956

/cc @josegonzalez @michaelshobbs

### CODE REVIEW

**Comment by josegonzalez** [comment]
Uh, you're gonna have to not delete some of that stuff...

**Comment by trevorturk** [comment]
Are you referring to the top part with the `checks` shell commands? I assumed that section must be outdated since I couldn't find the commands in `dokku help` but maybe not?

**Comment by josegonzalez** [comment]
Yes, that needs to stay. It's part of the upcoming 0.5.x release.

**Comment by josegonzalez** [comment]
You totally do not need to open a new pull request, simply force push to the same branch and it will update the commits in the pull request.

**Comment by trevorturk** [comment]
Oh, sorry, I didn't realize that. Please just use #1965 and I'll update that with a force push if needed.

**Pull request closed without merging**
