### PR TITLE
Attempt to support strings with double-quotes

### PR DESCRIPTION
**Pull request by josegonzalez**
This is probably not the best way, but I'm trying it nonetheless.

Refs #1262

### CODE REVIEW

**Comment by josegonzalez** [comment]
I was thinking about this a bit more, and perhaps a cleaner way would be to do something like the following (pseudocode btw):

```
TMP=create_tmp_env_dir_on_host
for value in app_config; do
    echo "$VALUE" > "TMP/$KEY"
done
docker run -v $TMP:/tmp/env /bin/bash -c '/bin/bash /tmp/set_env.sh'
```

Would avoid all the sed calls and potentially allow us to have an easier time of handling various types of values...

**Comment by josegonzalez** [comment]
Another attempt could be to build a non-exported version of the config vars:

```
 dokku config --shell python-sample > $TMP/file
docker run -v $TMP:/tmp/mounted-env /bin/bash -c 'mkdir /tmp/env && for key in file; do WRITE_VALUE; done'
```

**Comment by josegonzalez** [comment]
Ugh tests

**Comment by cu12** [comment]
Without trying I was wondering if `printf %q` could be in help here? I'm using that quite successfully for complicated MySQL queries over ssh.

http://wiki.bash-hackers.org/commands/builtin/printf

**Pull request merged**
