### PR TITLE
Migrate all dokku related configuration to filedb wrapper

### PR DESCRIPTION
**Pull request by josegonzalez**
This change allows us to stop polluting the environment
for deployed applications, making configuration setting/unsetting
a simple matter of calling filedb.

This change breaks compatibility with plugins that expected dokku
config to be available via `dokku config:get`, as it will also
silently migrate this configuration.

### CODE REVIEW

**Comment by michaelshobbs** [comment]
A few questions
- Why not migrate everything to filedb on install?
- Why change the call to `get_config_value` instead of just implementing it in `config_get`?
- Seems like we now have two methods to set/get config? Why?

**Comment by josegonzalez** [comment]
- Because not everyone installs via the deb packaging.
- Because then we'd need to have another flag to figure out if it's internal to dokku or called by a user.
- One is for application env config, the other is for general dokku-related configuration.

**Comment by michaelshobbs** [comment]
> Because not everyone installs via the deb packaging.

If you add it to the `install` trigger then it gets run on install....(see [here](https://github.com/dokku/dokku/blob/v0.5.4/plugins/checks/install#L6-L39))

>Because then we'd need to have another flag to figure out if it's internal to dokku or called by a user.

ok. docs will make that clear. might want to add that to the PR details? It's not clear when a developer might use one over the other.

>One is for application env config, the other is for general dokku-related configuration.

again, docs (of course :smile:)

**Comment by josegonzalez** [comment]
Yeah, need to write docs in the plugin creation section for sure. Not sure why tests are failing yet...

**Comment by michaelshobbs** [comment]
Also a meta question, any reason to add the complexity of file-db and not just move the location of config using the same interface we have today?

**Comment by josegonzalez** [comment]
I wanted to be able to do something like:

```
# provides filedb binary with a different backend
apt-get install consuldb
```

And have dokku-level configuration persist outside of the config plugin. Shipped dokku images have the build-env already set, so we need a way to persist dokku config outside of that if the dokku image is run on a separate machine.

**Comment by michaelshobbs** [comment]
I'll withhold further comment until you've fleshed this out. I'm still not clear why we have two methods of setting config.

**Pull request closed without merging**
