### PR TITLE
Add dokku-limit to plugins documentation

### PR DESCRIPTION
**Pull request by sarendsen**
[ci skip]

### CODE REVIEW

**Comment by josegonzalez** [comment]
Will merge this once https://github.com/sarendsen/dokku-limit/issues/1 is fixed ;)

**Comment by josegonzalez** [comment]
Also this is something I'd love to see in the core... I even wrote a blog post about how this might work :)

**Comment by sarendsen** [comment]
Done, yes hopefully this can be build out to something more integrated. Though first some stuff in core needs some love like docker-options supporting processes and maybe some service hooks so we can limit service containers aswell.

**Comment by josegonzalez** [comment]
I think service hooks are a bit different from this, and the underlying plugins should implement that themselves.

We can at least support the current method of applying limits across a service, which is what your plugin does.

**Comment by sarendsen** [comment]
Thats true, ill seperate resource logic and app logic soon so its more reusable outside of the apps score.

**Pull request merged**
