### PR TITLE
Use non-deprecated apps command

### PR DESCRIPTION
**Pull request by adelq**
[ci skip]

### CODE REVIEW

**Comment by josegonzalez** [comment]
I think apps:list is fairly new so users of older versions will have trouble with this change. Might be worth mentioning that instead.

**Comment by wiredmind** [comment]
This commit applies to the latest version, doesn't it? In which case this should not cause confusion, but perhaps there should be a note for users of older versions to check the documentation for their version.

**Comment by josegonzalez** [comment]
> I think apps:list is fairly new so users of older versions will have trouble with this change. Might be worth mentioning that instead.

**Comment by josegonzalez** [comment]
I clarified the docs since no one seemed interested in doing so. Thanks for the initial contribution though!

**Pull request merged**
