### PR TITLE
filter restart policies from exec-app-json containers

### PR DESCRIPTION
**Pull request by michaelshobbs**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Is it possible to test this?

**Comment by michaelshobbs** [comment]
I tested locally. You think we need a unit test?

**Comment by josegonzalez** [comment]
Maybe? I vaguely recall us saying there were other args that couldn't be applied to certain phases. I'm fine with merging either way.

**Comment by michaelshobbs** [comment]
We have that other filtering in place in the docker-options plugin itself. This is sort of a special edge case (aren't they all?!) that's specific to restart policies and the pre/post deploy containers. i.e. we want to include the deploy docker-options because we want that container to look as much like the actual deployed container as possible but the restart policy doesn't make sense to include.

**Comment by josegonzalez** [comment]
Gotcha. Again, works for me if you feel it's good to merge :)

**Comment by michaelshobbs** [comment]
I reserve the right to add a test in the future. (maintainers prerogative :wink:)

**Pull request merged**
