### PR TITLE
Add newline character when printing config:get

### PR DESCRIPTION
**Pull request by shrmnk**
## What

Adds a newline character at the end of `dokku config:get` output

### CODE REVIEW

**Comment by josegonzalez** [comment]
@michaelshobbs any idea what that error is about? Seems kinda strange.

**Comment by michaelshobbs** [comment]
Looks like there something wrong with either the github fork or circleci. The build is happening under the fork’s org and not dokku. :shrug:

**Comment by michaelshobbs** [comment]
Probably best to merge this via a new PR opened by someone with write access to the dokku project  maybe?

**Comment by josegonzalez** [comment]
@michaelshobbs did you end up merging this elsewhere?

**Comment by michaelshobbs** [comment]
I do not think so

**Comment by josegonzalez** [comment]
I resubmitted this as a new pull request.

**Pull request closed without merging**
