### PR TITLE
Purge cache for all apps when calling buildpacks:set-property with --global flag

### PR DESCRIPTION
**Pull request by elhu**
Fixes dokku#4990

### CODE REVIEW

**Comment by josegonzalez** [comment]
Any chance you can add a test for this?

**Comment by elhu** [comment]
For sure! Any pointers on where to look?

**Comment by josegonzalez** [comment]
I would create a test that runs the command and checks for zero exit code.

**Comment by elhu** [comment]
Got it, I'll see if I can add that today or tomorrow.

**Comment by elhu** [comment]
Alright, I have a test, let's see if that works!

**Pull request merged**
