### PR TITLE
Add skip_keyfile option for deb package

### LINKED ISSUE #1851: Unattended upgrade is not working
When running an Unattended upgrade, I still get the following question:

```
Configuring dokku
-----------------
Enable the web-based config page?
```

I use the following command: `$ sudo apt-get install -qq -y dokku`. Is this something I'm doing wrong?

### PR DESCRIPTION
**Pull request by jvanbaarsen**
There are cases where we don't want the check for keyfile, this will add a
config option, that allows you to skip this particular check.

Fixes #1851

### CODE REVIEW

**Comment by josegonzalez** [comment]
- What happens if this value isn't set?
- Doesn't this need to be handled somehow [here](https://github.com/dokku/dokku/blob/master/debian/config)?
- Do we need a debconf template for it [here](https://github.com/dokku/dokku/blob/master/debian/templates)?

**Comment by jvanbaarsen** [comment]
@josegonzalez Let me check every one of those cases!

For the template, I only feel that is needed if we also document this feature, what do you think?

**Comment by josegonzalez** [comment]
Oh yeah, this also needs to be documented.

**Comment by jvanbaarsen** [comment]
:+1: On it!

**Comment by jvanbaarsen** [comment]
@josegonzalez When I add the following to debian/config, the installation will break:

```
db_input "high" "dokku/skip_key_file" || false
```

Can I only put `true` on the right side?

**Comment by josegonzalez** [comment]
Idk @3onyc implemented this. You're gonna have to go debian packaging spelunking :D

**Comment by jvanbaarsen** [comment]
@josegonzalez Ok, what about I just make sure I get it to work for the old scenario, and the new scenario, If that works without touching the config, would that be ok for you?

**Comment by josegonzalez** [comment]
Yeah. The following should work:

- Fresh install with web config
- Fresh install/Upgrade with debconf
- Fresh install/Upgrade with prompts

**Comment by jvanbaarsen** [comment]
@josegonzalez Also, when I add it to the `template` file, it will ask in the GUI prompts if you want to skip the key_file. I feel that should not be there, right? Since its only for fully unattended installations?

**Comment by josegonzalez** [comment]
If thats the case, I guess you can leave it off.

**Comment by 3onyc** [comment]
@jvanbaarsen If I recall correctly only items listed in `debian/config` get asked to the user, so `dokku/skip_key_file` shouldn't be in there. However it should be added to `debian/templates`

Also, looking at your use case, you're already asking for IP/port to install Dokku, can't you also prompt for a public key there?

**Comment by jvanbaarsen** [comment]
@3onyc I'm skipping those questions as well with the config setters. Why should it be in debian/templates though?

**Comment by jvanbaarsen** [comment]
@josegonzalez I feel like this is ready to be merged

**Comment by 3onyc** [comment]
@jvanbaarsen It's the standard file to define all debconf values in, if we omit it Debian packaging related utilities won't know it exists.

**Comment by jvanbaarsen** [comment]
@3onyc I don't think that is a problem, since it mostly there for people that know what it is for. And not really for general use. @josegonzalez Opinion?

**Comment by josegonzalez** [comment]
I would go with what @3onyc says.

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
@josegonzalez Updated PR

**Comment by josegonzalez** [comment]
@3onyc I'll wait on your decision before merging :)

**Comment by jvanbaarsen** [comment]
@3onyc Bump :-)

**Comment by 3onyc** [comment]
Already merged, but :+1:.

**Comment by jvanbaarsen** [comment]
@3onyc / @josegonzalez Thanks!

**Pull request merged**
