### PR TITLE
Add reference to external post-deploy-script plugin

### PR DESCRIPTION
**Pull request by baikunz**
[ci skip]

Referenced a plugin I made to execute scripts after a deploy.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Just a note, you shouldn't store things in the git directory, and instead use either a config/data directory like:

```
/var/lib/dokku/data/PLUGIN_NAME/APP_NAME/whatever
```

Dokku will be a refactoring the app directory to remove it's own mis-usage of it in the future.

**Comment by baikunz** [comment]
Well I thought about what you said regarding not storing things in the git directory. Is there any reason for that ?
Because I thought about using your `dokku-supply-config` plugin to copy the `POST_DEPLOY_SCRIPT` I'm using on my plugin.
Is it planned that you update your plugin to support this new folder structure ?

**Comment by josegonzalez** [comment]
Yeah I don't think thats the correct pattern, as it makes it hard for us to version configuration or store it in a different datastore. See #1558 for more details.

**Comment by baikunz** [comment]
Thanks for pointing it out. It makes more sense now. I was not aware of that since I just started using dokku.
Regarding the plugin, I will change the location of the file according to your suggestion.
However until the `dokku-supply-config` plugin is updated, we won't be able to copy this file in it's new location automatically. So it will have to be created manually.

**Comment by josegonzalez** [comment]
Would be a good pr to that plugin :)

**Comment by baikunz** [comment]
Yea sure ;-)
But there is quite some work to be done, because the files will now be copied into multiple directories.

**Pull request merged**
