### PR TITLE
fix: define devcontainer platform

### PR DESCRIPTION
**Pull request by nerg4l**
AMD64 version of Go is installed inside the devcontainer but the platform of dokku image is not defined. The platform of the image has to be defined for ARM devices because on these machines ARM version of dokku image is used by default.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Worth fixing the golang version to support arm architectures instead?

**Comment by nerg4l** [comment]
I will have a look on that.

**Comment by nerg4l** [comment]
I keep running into the following error message on M1 when I try to use linux/arm64 platform:

```
------
 > [internal] load build context:
------
error from sender: failed to xattr /Users/lgorog/GolandProjects/dokku/tmp/data/etc/ssh/sedg8XNmt: permission denied
```

**Comment by josegonzalez** [comment]
Might be this: https://github.com/dokku/dokku/blob/82778a0aad16605a0681c7d87f5b9bec5610f439/docker/etc/my_init.d/10_dokku_init#L44

**Comment by nerg4l** [comment]
It is somehow caused by `COPY . .`

**Comment by nerg4l** [comment]
Okay, it turns out was caused by `dokku/tmp` dir after removing it I run into a new problem 😄 

```
executor failed running [/bin/sh -c wget https://dl.google.com/go/go1.17.9.linux-arm64.tar.gz]: exit code: 5
```

**Comment by josegonzalez** [comment]
Weird, that definitely is downloadable by me...

**Comment by nerg4l** [comment]
With `--no-check-certificate` flag it works fine. Why the cert is not accepted.

**Comment by josegonzalez** [comment]
Is there a better download url? Maybe we need ca-certificates update or something on arm.

Also maybe upgrading the focal image works: https://github.com/phusion/baseimage-docker/releases/tag/focal-1.2.0

**Comment by nerg4l** [comment]
I tried

```
RUN apt-get install -y ca-certificates
```

which caused `exit code 100` so I added

```
RUN apt-get update && apt-get install -y apt-transport-https
```

and now it seems to be working

**Comment by nerg4l** [comment]
Now if I try to open the devcontainer in VSCode I get the following:

```
[2022-05-19T21:14:17.847Z] Remote-Containers 0.234.0 in VS Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5).
[2022-05-19T21:14:17.847Z] Start: Resolving Remote
[2022-05-19T21:14:17.877Z] Setting up container for folder or workspace: /Users/lgorog/GolandProjects/dokku/workspace.code-workspace
[2022-05-19T21:14:17.880Z] Start: Check Docker is running
[2022-05-19T21:14:17.880Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-05-19T21:14:17.963Z] Stop (83 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-05-19T21:14:17.964Z] Server API version: 1.41
[2022-05-19T21:14:17.964Z] Stop (84 ms): Check Docker is running
[2022-05-19T21:14:17.964Z] Start: Run: docker volume ls -q
[2022-05-19T21:14:18.025Z] Stop (61 ms): Run: docker volume ls -q
[2022-05-19T21:14:18.041Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/lgorog/GolandProjects/dokku --filter label=vsch.quality=stable
[2022-05-19T21:14:18.108Z] Stop (67 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/lgorog/GolandProjects/dokku --filter label=vsch.quality=stable
[2022-05-19T21:14:18.108Z] Start: Run: /Applications/VSCode.app/Contents/MacOS/Electron /Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/lgorog/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/lgorog/GolandProjects/dokku --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/lgorog/GolandProjects/dokku --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/lgorog/GolandProjects/dokku/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-19T21:14:18.205Z] remote-containers 0.234.0.
[2022-05-19T21:14:18.205Z] Start: Resolving Remote
[2022-05-19T21:14:18.207Z] Running the initializeCommand from devcontainer.json...

[2022-05-19T21:14:18.207Z] Start: Run: mkdir -p tmp/data
[2022-05-19T21:14:18.259Z] Stop (52 ms): Run: mkdir -p tmp/data
[2022-05-19T21:14:18.259Z] 
[2022-05-19T21:14:18.259Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/lgorog/GolandProjects/dokku --filter label=vsch.quality=stable
[2022-05-19T21:14:18.356Z] Stop (97 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/lgorog/GolandProjects/dokku --filter label=vsch.quality=stable
[2022-05-19T21:14:18.357Z] Start: Run: docker build -f /Users/lgorog/GolandProjects/dokku/.devcontainer/Dockerfile -t vsc-dokku-9740b059c04429e75e6be27df3b01d85 /Users/lgorog/GolandProjects/dokku
[2022-05-19T21:14:18.623Z] [+] Building 0.0s (0/1)                                                         
[2022-05-19T21:14:18.774Z] [+] Building 0.2s (2/3)                                                         
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.1s
[2022-05-19T21:14:18.925Z] [+] Building 0.3s (2/3)                                                         
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.2s
[2022-05-19T21:14:19.076Z] [+] Building 0.5s (2/3)                                                         
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.4s
[2022-05-19T21:14:19.227Z] [+] Building 0.6s (2/3)                                                         
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.5s
[2022-05-19T21:14:19.227Z] 
[2022-05-19T21:14:19.378Z] [+] Building 0.8s (5/15)                                                        
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.6s
 => [internal] load build context                                          0.0s
 => => transferring context: 44.80kB                                       0.0s
 => [ 1/10] FROM docker.io/library/ubuntu:latest@sha256:26c68657ccce2cb0a  0.0s
 => https://raw.githubusercontent.com/dokku/dokku/master/tests/dhparam.pe  0.1s
[2022-05-19T21:14:19.528Z] [+] Building 0.9s (5/15)                                                        
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
[2022-05-19T21:14:19.528Z]  => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.6s
 => [internal] load build context                                          0.0s
 => => transferring context: 44.80kB                                       0.0s
 => [ 1/10] FROM docker.io/library/ubuntu:latest@sha256:26c68657ccce2cb0a  0.0s
 => https://raw.githubusercontent.com/dokku/dokku/master/tests/dhparam.pe  0.3s
[2022-05-19T21:14:19.673Z] [+] Building 1.1s (6/15)                                                        
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.6s
 => [internal] load build context                                          0.0s
 => => transferring context: 44.80kB                                       0.0s
 => [ 1/10] FROM docker.io/library/ubuntu:latest@sha256:26c68657ccce2cb0a  0.0s
 => https://raw.githubusercontent.com/dokku/dokku/master/tests/dhparam.pe  0.4s
[2022-05-19T21:14:19.826Z] [+] Building 1.2s (15/16)                                                       
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.6s
 => [internal] load build context                                          0.0s
 => => transferring context: 44.80kB                                       0.0s
 => [ 1/10] FROM docker.io/library/ubuntu:latest@sha256:26c68657ccce2cb0a  0.0s
 => https://raw.githubusercontent.com/dokku/dokku/master/tests/dhparam.pe  0.4s
 => CACHED [ 2/10] RUN apt-get update &&   apt-get install -y apt-transpo  0.
[2022-05-19T21:14:19.826Z] 0s
 => CACHED [ 3/10] RUN apt-get install --no-install-recommends -y build-e  0.0s
 => CACHED [ 4/10] RUN wget https://dl.google.com/go/go1.17.9.linux-arm64  0.0s
 => CACHED [ 5/10] RUN GOROOT=/usr/local/go /usr/local/go/bin/go install   0.0s
 => CACHED [ 6/10] ADD https://raw.githubusercontent.com/dokku/dokku/mast  0.0s
 => CACHED [ 7/10] COPY .devcontainer/bin/ /usr/local/bin/                 0.0s
 => CACHED [ 8/10] COPY [tests.mk, Makefile]                               0.0s
 => CACHED [ 9/10] RUN make ci-dependencies                                0.0s
 => [10/10] COPY . .                                                       0.1s
 => exporting to image                                                     0.1s
 => => exporting layers                                                    0.1s
[2022-05-19T21:14:19.834Z] [+] Building 1.2s (16/16) FINISHED                                              
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
[2022-05-19T21:14:19.834Z]  => [internal] load metadata for docker.io/library/ubuntu:latest           0.6s
 => [internal] load build context                                          0.0s
 => => transferring context: 44.80kB                                       0.0s
 => [ 1/10] FROM docker.io/library/ubuntu:latest@sha256:26c68657ccce2cb0a  0.0s
 => https://raw.githubusercontent.com/dokku/dokku/master/tests/dhparam.pe  0.4s
 => CACHED [ 2/10] RUN apt-get update &&   apt-get install -y apt-transpo  0.0s
 => CACHED [ 3/10] RUN apt-get install --no-install-recommends -y build-e  0.0s
 => CACHED [ 4/10] RUN wget https://dl.google.com/go/go1.17.9.linux-arm64  0.0s
 => CACHED [ 5/10] RUN GOROOT=/usr/local/go /usr/local/go/bin/go install   0.0s
 => CACHED [ 6/10] ADD https://raw.githubusercontent.com/dokku/dokku/mast  0.0s
 => CACHED [ 7/10] COPY .devcontainer/bin/ /usr/local/bin/                 0.0s
 => CACHED [ 8/10] COPY [test
[2022-05-19T21:14:19.834Z] s.mk, Makefile]                               0.0s
 => CACHED [ 9/10] RUN make ci-dependencies                                0.0s
 => [10/10] COPY . .                                                       0.1s
 => exporting to image                                                     0.1s
 => => exporting layers                                                    0.1s
 => => writing image sha256:d15c143dc79c8a2c09fc29caedc4a7c7864037e57d8b6  0.0s
 => => naming to docker.io/library/vsc-dokku-9740b059c04429e75e6be27df3b0  0.0s
[2022-05-19T21:14:19.896Z] 
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[2022-05-19T21:14:19.901Z] Stop (1544 ms): Run: docker build -f /Users/lgorog/GolandProjects/dokku/.devcontainer/Dockerfile -t vsc-dokku-9740b059c04429e75e6be27df3b01d85 /Users/lgorog/GolandProjects/dokku
[2022-05-19T21:14:19.902Z] Start: Run: docker inspect --type image vsc-dokku-9740b059c04429e75e6be27df3b01d85
[2022-05-19T21:14:19.959Z] Stop (57 ms): Run: docker inspect --type image vsc-dokku-9740b059c04429e75e6be27df3b01d85
[2022-05-19T21:14:19.959Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-05-19T21:14:19.960Z] Start: Starting container
[2022-05-19T21:14:19.960Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/lgorog/GolandProjects/dokku,target=/root/go/src/github.com/dokku/dokku,consistency=cached --mount source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind --mount source=/Users/lgorog/GolandProjects/dokku/tmp/data/,target=/mnt/dokku/,type=bind --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/Users/lgorog/GolandProjects/dokku -l vsch.quality=stable -e DOKKU_HOST_ROOT=/Users/lgorog/GolandProjects/dokku/tmp/data/home/dokku -e GO_ROOT_MOUNT=/Users/lgorog/GolandProjects/dokku:/go/src/github.com/dokku/dokku --init --entrypoint /bin/sh vsc-dokku-9740b059c04429e75e6be27df3b01d85 -c echo Container started
[2022-05-19T21:14:20.416Z] Container started
[2022-05-19T21:14:20.423Z] Stop (463 ms): Starting container
[2022-05-19T21:14:20.423Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/lgorog/GolandProjects/dokku --filter label=vsch.quality=stable
[2022-05-19T21:14:20.494Z] Stop (71 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/lgorog/GolandProjects/dokku --filter label=vsch.quality=stable
[2022-05-19T21:14:20.494Z] Start: Run: docker inspect --type container 09db13ccee29
[2022-05-19T21:14:20.551Z] Stop (591 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/lgorog/GolandProjects/dokku,target=/root/go/src/github.com/dokku/dokku,consistency=cached --mount source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind --mount source=/Users/lgorog/GolandProjects/dokku/tmp/data/,target=/mnt/dokku/,type=bind --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/Users/lgorog/GolandProjects/dokku -l vsch.quality=stable -e DOKKU_HOST_ROOT=/Users/lgorog/GolandProjects/dokku/tmp/data/home/dokku -e GO_ROOT_MOUNT=/Users/lgorog/GolandProjects/dokku:/go/src/github.com/dokku/dokku --init --entrypoint /bin/sh vsc-dokku-9740b059c04429e75e6be27df3b01d85 -c echo Container started
[2022-05-19T21:14:20.560Z] Stop (66 ms): Run: docker inspect --type container 09db13ccee29
[2022-05-19T21:14:20.561Z] Start: Inspecting container
[2022-05-19T21:14:20.561Z] Start: Run: docker inspect --type container 09db13ccee29f52633cd8384796263287f73867c2e622a2616e9177d54130de3
[2022-05-19T21:14:20.623Z] Stop (62 ms): Run: docker inspect --type container 09db13ccee29f52633cd8384796263287f73867c2e622a2616e9177d54130de3
[2022-05-19T21:14:20.623Z] Stop (62 ms): Inspecting container
[2022-05-19T21:14:20.624Z] Start: Run in container: /bin/sh
[2022-05-19T21:14:20.625Z] Start: Run in container: uname -m
[2022-05-19T21:14:20.695Z] Stop (71 ms): Run in container: /bin/sh
[2022-05-19T21:14:20.695Z] Shell server terminated (code: 1, signal: null)
[2022-05-19T21:14:20.695Z] Error response from daemon: Container 09db13ccee29f52633cd8384796263287f73867c2e622a2616e9177d54130de3 is not running
[2022-05-19T21:14:20.695Z] Start: Run in container: cat /etc/passwd
[2022-05-19T21:14:20.695Z] Stdin closed!
[2022-05-19T21:14:20.696Z] Error: An error occurred setting up the container.
[2022-05-19T21:14:20.696Z]     at IR (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:995)
[2022-05-19T21:14:20.696Z]     at zy (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:933)
[2022-05-19T21:14:20.696Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-05-19T21:14:20.696Z]     at async $R (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:2007)
[2022-05-19T21:14:20.696Z]     at async Zy (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:3112)
[2022-05-19T21:14:20.696Z]     at async BR (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12448)
[2022-05-19T21:14:20.696Z]     at async qR (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12204)
[2022-05-19T21:14:20.698Z] Stop (2590 ms): Run: /Applications/VSCode.app/Contents/MacOS/Electron /Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/lgorog/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/lgorog/GolandProjects/dokku --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/lgorog/GolandProjects/dokku --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/lgorog/GolandProjects/dokku/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-19T21:14:20.698Z] Exit code 1
[2022-05-19T21:14:20.699Z] Command failed: /Applications/VSCode.app/Contents/MacOS/Electron /Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/lgorog/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/lgorog/GolandProjects/dokku --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/lgorog/GolandProjects/dokku --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/lgorog/GolandProjects/dokku/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-19T21:14:20.699Z] Exit code 1
```

**Comment by josegonzalez** [comment]
Thats strange, we don't open that file in this codebase.

What happens if you replace the devcontainer Dockerfile with the upstream `phusion/baseimage:focal-1.1.0` image (with nothing else)?

**Comment by nerg4l** [comment]
I tried again after stopping and removing everything to cleanup the mess. The currently pushed version seems to be working.

```
# uname -a
Linux b755e6a18681 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```


The next I error I run into when I tried to push a project but I think that's caused by a different issue. I tried it with both architecture types on M1.

```
------
 > [internal] load metadata for docker.io/dokku/ruby-getting-started:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
remote:  !     Failure injecting BUILD_ENV into build environment
remote: 2022/05/21 18:26:06 exit status 1
remote: 2022/05/21 18:26:06 exit status 1
remote:  !     Removing invalid image tag dokku/ruby-getting-started:latest
remote:  !     App build failed
To dokku.me:ruby-getting-started
 ! [remote rejected] main -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku.me:ruby-getting-started'
```

**Comment by josegonzalez** [comment]
You can't use herokuish on arm instances. In the devcontainer, what is the output of `dpkg --print-architecture`?

**Comment by nerg4l** [comment]
```
# dpkg --print-architecture
arm64
```

But the build starts with the following:

```
# git push dokku main:master
Pseudo-terminal will not be allocated because stdin is not a terminal.
Enumerating objects: 450, done.
Counting objects: 100% (450/450), done.
Delta compression using up to 4 threads
Compressing objects: 100% (242/242), done.
Writing objects: 100% (450/450), 98.33 KiB | 98.33 MiB/s, done.
Total 450 (delta 181), reused 449 (delta 180)
remote: Resolving deltas: 100% (181/181), done.
-----> Cleaning up...
-----> Building ruby-getting-started from herokuish
remote: WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
-----> Adding BUILD_ENV to build environment...
```

Because of the warning I would guess it tries to use `linux/amd64` of `herokuish`.

**Comment by nerg4l** [comment]
```
$ docker run --rm -v /abs/app/path:/tmp/app gliderlabs/herokuish /bin/herokuish test
```

Command seem to work correctly on arm64. Output: https://gist.github.com/nerg4l/bce69372d17cb50a940285bd851d4c8f

**Comment by josegonzalez** [comment]
Yeah we should disable herokuish on arm64 in the `builder-herokuish/builder-detect` file.

**Comment by josegonzalez** [comment]
I redid this in #5392 since I had to switch to an ARM64 machine. No tests with herokuish will work (because herokuish isn't built/released for ARM/ARM64 as most/all of the buildpacks won't work) but thats okay.

Thanks for providing the groundwork here, it was super useful!

**Pull request closed without merging**
