### PR TITLE
Allow hyphen in TLD

### LINKED ISSUE #2359: domains:add rejects domains with hyphen in host path
Description of problem:
domains:add rejects domains that contain a hyphen in the host path e.g. dokku.my-server

How was dokku installed?: apt-get

Dokku version: 0.7.0

How reproducible: easily

Steps to Reproduce:
1. dokku domains:add <app_name> dokku.my-server

Actual Results: 
dokku.my-server is invalid. exiting...

Expected Results:
domain added

We face this issue running dokku in a private network.

### PR DESCRIPTION
**Pull request by xadh00m**
Fixes #2359

### CODE REVIEW

**Comment by xadh00m** [comment]
This also removes the restriction that the last host part needs to consist of at least two characters. Is this an issue?

**Comment by jvanbaarsen** [comment]
I think leaving the at least 2 characters for tld in there makes sense. Since it is a requirement. Also not really sure about allowing the hyphen. I went over available tld list, and no tld has a hyphen in there. /cc @josegonzalez

**Comment by xadh00m** [comment]
We use dokku in a company private network where they use hyphen in the tld (like "backend.i-robot").
I think its fine to relax the validation. AFAIK the whole validation has been introduced to prevent user from entering uris like: "http://dokku.me".

How should the requirement for at least two characters look like with hyphen?

**Comment by josegonzalez** [comment]
Needs tests before I'll merge this.

**Comment by znz** [comment]
IDN TLD have `--`. see https://github.com/dokku/dokku/issues/2318#issuecomment-233016277
And including `---` is valid domain. for example: https://github.com/plataformatec/devise/blob/6720f93d2c54904f10b6e6d6beb51d0b5b330976/test/devise_test.rb#L97

**Comment by josegonzalez** [comment]
Awesome, that works for me.

@xadh00m mind updatnig the tests to include the domain from #2318?

**Comment by jvanbaarsen** [comment]
@josegonzalez / @xadh00m Aren't they talking about the domain part itself? not the tld? as in:

**Allowed**: domain--name-with-hyphen.com
**not allowed**: domain.hi--there

**Comment by xadh00m** [comment]
I did not (yet) find a clear statement regarding IDN TLDs with one ore more hyphen in the ICANN specs.

@znz: How did you get the IDNs with hyphens in the TLD mentioned in your [comment](https://github.com/dokku/dokku/issues/2318#issue-165784999)?

**Comment by xadh00m** [comment]
At least there seem to be no practially used [gTLDs](https://domaintyper.com/domain-names/top-level-domains/new-gTLD) with hyphens yet.

Anyway, Dokku is used in private networks with custom domain name policies in place.
Should Dokku enforce any kind of spec here? Should Dokku help the user typing the domain correctly according to the latest IDN specs (if that is even possible with a regex)?

The [initial intention](https://github.com/dokku/dokku/issues/2231) of the validation was to ensure that the user does not type "http://dokku.me" but "dokku.me" which made the API clear and prevented a specific error case.

**Comment by jvanbaarsen** [comment]
@xadh00m I don't think the main use case for Dokku is to be within a private network.

**Comment by xadh00m** [comment]
I agree that it might not be the main use case but its an actual use case and might be worth supporting it.

**Comment by znz** [comment]
Examples are from JPNIC's web sites.
https://www.nic.ad.jp/ja/basics/terms/idntld.html
http://punycode.jp/

`IDNs non Ascii` are gTLDs with hyphens, because there are encoded as [Punycode](https://en.wikipedia.org/wiki/Punycode).
For example, `みんな` gTLD is `xn--q9jyb4c`.

**Comment by josegonzalez** [comment]
@xadh00m can you update your pr to add a few tests for hyphens in the tld? That would at least be a step in the right direction, and I'd be happy to support that use case.

**Comment by xadh00m** [comment]
I´ve updated the regex and added a test case accordingly.

**Comment by xadh00m** [comment]
See [regexper](https://regexper.com/#%5E(%5Ba-z0-9%5C*-%5D%2B%5C.)*%5Ba-z0-9%5C*-%5D%2B%24) for details.

**Pull request merged**
