### PR TITLE
Expand docs surrounding access control

### PR DESCRIPTION
**Pull request by ltalirz**
[ci skip]

The deployment documentation on scoping user access pointed only to the
development documentation for implementing plugins to handle user
scoping.
Added link to the dokku-acl plugin, which already handles user scoping
out of the box.

### CODE REVIEW

**Comment by josegonzalez** [comment]
I don't want to do this. It's not an official plugin, so it should only be pointed out on our plugin index page.

**Comment by ltalirz** [comment]
Up to you, of course.
It's just that this place in the documentation is where I ended up looking for how to do user management, and the link provided was not very helpful - that's why I needed to ask in the slack channel.

**Comment by ltalirz** [comment]
One could suggest to have a look at the plugin page

**Comment by josegonzalez** [comment]
Might be better to point to the plugin page. Do we have other auth plugins around?

**Comment by ltalirz** [comment]
There's http auth, but in terms of management for docker users I don't see another one in the list

**Comment by ltalirz** [comment]
I've now removed the explicit mention of dokku-acl and replaced it by a link to the list of contributed plugins.
I find it a bit less helpful than mentioning dokku-acl directly, but still better than before.

**Pull request merged**
