### PR TITLE
Checks example tweaks 2

### PR DESCRIPTION
**Pull request by trevorturk**
Followup re: #1964 @josegonzalez holler if you'd like any other changes.

### CODE REVIEW

**Comment by josegonzalez** [comment]
What exactly are you trying to add in this pr? I feel as though you might be changing more than you need to...

**Comment by trevorturk** [comment]
I found this part of the documentation confusing, so I edited the awkwardly worded sections, changed a bit of the ordering, and added a bit about bypassing the default wait time as per #1956. 

I think this is much better than it was, but if you'd prefer, I can reset and just add the bit about the default wait time as per #1956 and force push.

**Comment by josegonzalez** [comment]
Can you split your changes into a series of commits so I can review them one by one? That'll make your changes much more clear to me.

**Comment by trevorturk** [comment]
Ok, I'll work on that tomorrow and force push here. Thanks!

**Comment by trevorturk** [comment]
I broke apart my reworking of this documentation into commits so it should be easier to follow my logic and to make sure I didn't inadvertently introduce errors. 

FWIW I'd like to point out that I did a similar rewrite of the `Devise` documentation when I first started using it. I redid the `README` and reorganized the wiki: https://github.com/plataformatec/devise/commits?author=trevorturk

I also did a lot of documentation work for Rails: https://github.com/rails/rails/commits?author=trevorturk

(I noticed you mentioned Devise on your blog post on open source http://josediazgonzalez.com/2016/01/26/open-source-is-hard/ so I thought I should point out my documentation contributions elsewhere and apologize for giving you a big chunk of commits to review. I think my changes improve the documentation enough to warrant the trouble, and hopefully you'll agree, but no worries if not. I'm just trying to give back to dokku a bit because I've been really enjoying working with it for the last week or two. Thank you!)

**Comment by josegonzalez** [comment]
Doc changes seem reasonable to me.

Note: for docs changes, it's helpful to add the following so circleci doesn't try and build them:

```
[ci skip]
```

**Comment by trevorturk** [comment]
Thank you! I'll use `[ci skip]` next time.

**Comment by josegonzalez** [comment]
Feel more than free to do similar work for other docs.

**Comment by trevorturk** [comment]
Thanks -- I'll work up more PRs if I run into any more confusing bits. This was all I found so far, and I almost have my first server up and running. (Good job with the docs!) 

I'm planning on publishing a "how I moved my app from Heroku to dokku" gist once I'm done, so maybe that'll be helpful for other people down the road, too.

**Pull request merged**
