### PR TITLE
Add ElasticMQ plugin to documentation

### PR DESCRIPTION
**Pull request by cu12**
Again ^^

### CODE REVIEW

**Comment by michaelshobbs** [comment]
Why again?

**Comment by cu12** [comment]
@michaelshobbs You merged my FakeSNS plugin yesterday ;)

**Comment by michaelshobbs** [comment]
Ah ok. Curious, what do both of those plugins do?

**Comment by cu12** [comment]
FakeSNS mimics the behaviour of [Amazon SNS](https://aws.amazon.com/sns/) and [ElasticMQ](https://github.com/adamw/elasticmq) does the same for [Amazon SQS](https://aws.amazon.com/sqs/).

We're using Dokku as a core component in our QA environment. Since we use SNS and SQS services, I created these to be able to test everything we need (mostly :)). I hope others will find them useful as well.

**Comment by michaelshobbs** [comment]
Excellent! Thanks for the share.

**Pull request merged**
