### PR TITLE
Make DOKKU_PROXY_PORT globally configurable

### PR DESCRIPTION
**Pull request by lalyos**
if dokku is installed on a host where port 80 is already used by some other service,
you have to set `DOKKU_PROXY_PORT` for each app separately.

This change would check the global config `DOKKU_PROXY_PORT` in case its not set, for the app.

If its not set in global scope, than the original default 80 is used.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you add a test for this?

**Comment by lalyos** [comment]
added test without patch:
```
$ tests/bats-exec-test-single   tests/unit/20_nginx-vhosts_1.bats global_DOKKU

Running test: test_(nginx-2dvhosts)_nginx:build-2dconfig_(global_DOKKU-5fPROXY-5fPORT)()
1..1
not ok 1 (nginx-vhosts) nginx:build-config (global DOKKU_PROXY_PORT)
# (from function `assert_success' in file tests/unit/test_helper.bash, line 37,
#  from function `check_urls' in file tests/unit/test_helper.bash, line 180,
```

after applied patch:
```
$ curl -LO https://github.com/dokku/dokku/pull/3789.patch | git apply -
$ tests/bats-exec-test-single   tests/unit/20_nginx-vhosts_1.bats global_DOKKU
Running test: test_(nginx-2dvhosts)_nginx:build-2dconfig_(global_DOKKU-5fPROXY-5fPORT)()
1..1
ok 1 (nginx-vhosts) nginx:build-config (global DOKKU_PROXY_PORT)
```

**Comment by josegonzalez** [comment]
Closing as circleci is doing something funky with the PR now that the branch accidentally was pushed to origin...

**Comment by josegonzalez** [comment]
Merged in #3844 .

**Pull request closed without merging**
