### PR TITLE
Do not remove unused image to hold tags

### PR DESCRIPTION
**Pull request by tribela**
Related: #4380

Dokku was removing all unused images and that causes removed tagged images.
This PR will fix that problem.

### CODE REVIEW

**Comment by josegonzalez** [comment]
```
% docker image prune -h
Flag shorthand -h has been deprecated, please use --help

Usage:  docker image prune [OPTIONS]

Remove unused images

Options:
  -a, --all             Remove all unused images, not just dangling ones
      --filter filter   Provide filter values (e.g. 'until=<timestamp>')
  -f, --force           Do not prompt for confirmation
```

Are you sure this is correct? The help output says its only unused images...

**Comment by tribela** [comment]
That "unused" means "currently not running images".
tags should not be removed even they are not running right now

**Comment by josegonzalez** [comment]
I don't think we should do this, as it will lead to folks having a ton of used up space and complaints that Dokku is leaving unused images around. Since the image is tagged with dokku's internal tag, I think we should assume Dokku is handling it's lifecycle.

Instead, it might be worth moving your workflow to the new `git:from-image` command?

**Comment by tribela** [comment]
Oh I didn't know that git:tags was deprecated and `git:from-image` command.
I want to move to that `from-image` deploy Cause I build the docker image separately with CI.
Can you tell me how the `git:from-image` triggers to update(pull) to new image?

**Comment by josegonzalez** [comment]
Docs here: https://dokku.com/docs/deployment/methods/git/#initializing-an-app-repository-from-a-docker-image

You will need to push the image to a registry and login as the dokku user.

**Comment by tribela** [comment]
So if I want to deploy new image, execute `git:from-image` command after pushing into docker registry?

**Comment by josegonzalez** [comment]
Yes.

**Pull request closed without merging**
