### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by znz**

### CODE REVIEW

**Comment by michaelshobbs** [comment]
Eek! That's a major typo 😁️

Perhaps there's something wrong with the IPv6 tests?

**Comment by josegonzalez** [comment]
Lmao. Welp merging.

**Comment by michaelshobbs** [comment]
@josegonzalez i think this is the original commit: https://github.com/dokku/dokku/commit/467264d31f929c13134ecd95eed08cc0ef99eded#diff-24a947d0d17068c3d22fbc3fb60fa554

**Comment by josegonzalez** [comment]
Welp that just means your original tests sucked :D

**Comment by michaelshobbs** [comment]
Perhaps

**Comment by michaelshobbs** [comment]
@znz did you hit a bug before fixing this? i'm curious because i'd like to fix the test suite to catch this. if so, can you share with us your configuration? (specifically any dokku config that contained IPv6 addresses. `/home/dokku/HOSTNAME`, `/home/dokku/VHOST`, `/home/dokku/$APP/VHOST`)

**Comment by znz** [comment]
No, I did not hit this bug.
I found it when I watch `git log -p --stat`.

**Pull request merged**
