### PR TITLE
update herokuish to 0.3.29

### PR DESCRIPTION
**Pull request by michaelshobbs**

### CODE REVIEW

**Comment by joshmanders** [comment]
I'm confused. This says updating to `0.3.29` but the commit has `0.3.24`

**Comment by josegonzalez** [comment]
fixed!

**Comment by joshmanders** [comment]
That's one way to do it. Was just not sure if it meant to be 0.3.24 or 0.3.29. :D

**Comment by michaelshobbs** [comment]
doh! Supposed to be 0.3.24. Was doing too many things at once. Unfortunately the git commit comment is wrong 😢

**Pull request merged**
